"""Response models for API endpoints."""
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field

from app.models.feature_models import PropertyFeaturesComplete, PropertyFeaturesPartial


class Stage1ExtractionResult(BaseModel):
    """
    Output from Stage 1 LLM extraction.
    
    Represents newly extracted features from the latest user message,
    along with completeness status and the next follow-up question.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "extracted_features": {
                    "YearBuilt": 2005,
                    "FullBath": 2,
                    "GarageCars": 1,
                },
                "missing_features": [
                    "OverallQual",
                    "GrLivArea",
                    "TotalBsmtSF",
                    "Neighborhood",
                    "ExterQual",
                    "KitchenQual",
                    "BsmtQual",
                    "TotRmsAbvGrd",
                    "LotArea",
                ],
                "is_complete": False,
                "assistant_message": "I still need the overall quality from 1 to 10, the above-ground living area in square feet, and the basement size in square feet.",
            }
        }
    )

    extracted_features: PropertyFeaturesPartial = Field(
        description="Features extracted from latest user message"
    )
    missing_features: List[str] = Field(
        description="Required features still missing after extraction"
    )
    is_complete: bool = Field(
        description="Whether all required features are now present"
    )
    assistant_message: str = Field(
        description="Follow-up question or completion message (generated by code, not LLM)"
    )


class IncompleteFeatureResponse(BaseModel):
    """
    Response returned when /predict is called but features are incomplete.
    
    This tells the client which features are missing and what to ask for next.
    Used when returning incomplete extraction status to the user.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "status": "needs_more_info",
                "extracted_features": {"GrLivArea": 1850.0},
                "accumulated_features": {
                    "YearBuilt": 2005,
                    "FullBath": 2,
                    "GrLivArea": 1850.0,
                },
                "missing_features": [
                    "OverallQual",
                    "TotalBsmtSF",
                    "GarageCars",
                    "Neighborhood",
                    "ExterQual",
                    "KitchenQual",
                    "BsmtQual",
                    "TotRmsAbvGrd",
                    "LotArea",
                ],
                "assistant_message": "I still need the overall quality from 1 to 10, the basement size in square feet, and the neighborhood name.",
            }
        }
    )

    status: str = Field(
        default="needs_more_info",
        description="Fixed status indicating incomplete extraction",
    )
    extracted_features: PropertyFeaturesPartial = Field(
        description="Features extracted in this turn"
    )
    accumulated_features: PropertyFeaturesPartial = Field(
        description="All known features accumulated so far (current state + extracted)"
    )
    missing_features: List[str] = Field(
        description="Required features still missing"
    )
    assistant_message: str = Field(
        description="Question asking for the next missing features"
    )


class HealthResponse(BaseModel):
    """GET /health endpoint response."""

    status: str = Field(description="Health status")
    message: Optional[str] = Field(default=None, description="Optional status message")


class PredictionResponse(BaseModel):
    """
    Response returned when /predict completes with a prediction.
    
    Contains the accumulated features, predicted sale price, and
    global statistics for context about the prediction.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "status": "success",
                "accumulated_features": {
                    "OverallQual": 8,
                    "GrLivArea": 2000.0,
                    "TotalBsmtSF": 1000.0,
                    "GarageCars": 2,
                    "Neighborhood": "CollgCr",
                    "ExterQual": "Gd",
                    "YearBuilt": 2005,
                    "FullBath": 2,
                    "KitchenQual": "Gd",
                    "BsmtQual": "Gd",
                    "TotRmsAbvGrd": 8,
                    "LotArea": 8200.0,
                },
                "predicted_price": 245000.50,
                "global_stats": {
                    "target_mean": 180921.0,
                    "target_std": 79442.5,
                    "target_min": 34900.0,
                    "target_max": 755000.0,
                },
            }
        }
    )

    status: str = Field(
        default="success",
        description="Status indicating prediction succeeded",
    )
    accumulated_features: PropertyFeaturesComplete = Field(
        description="All 12 features used for prediction"
    )
    predicted_price: float = Field(
        description="Predicted sale price in USD"
    )
    global_stats: Dict[str, Any] = Field(
        description="Global statistics from model artifact (e.g., target mean/std)",
    )

